// xem tất cả các post
GET http://localhost:5000/api/posts
Accept: application/json

###
// lấy 1 post bằng id
GET http://localhost:5000/api/posts/625fbab0802e34fc55a25341
Content-Type: application/json


###
#viewCount không cần gửi vì mặc định bằng 0
POST http://localhost:5000/api/posts
Content-Type: application/json

{
  "category": "Đồ điện tử",
  "subCategory": "Điện thoại",
  "zaloId": "3024770787876860996",
  "city": "Thủ Đức",
  "district": "Quận 9",
  "images": ["https://i.imgur.com/TyPdN9n.jpeg"],
  "status": "Active",
  "condition": "Đồ cũ",
  "title": "Bán Iphone 13 Pro Max xài lướt",
  "price": 10000000,
  "description": "Bán gấp Iphone 13 Pro Max, chỉ 20 triệu liên hệ ngay để ép giá!",
  "productDetails": {
    "color": "xanh"
  }
}


###
//tạo bài đăng có lỗi(thiếu zaloId, city)
POST http://localhost:5000/api/posts
Content-Type: application/json

{
  "category": "Đồ điện tử",
  "subCategory": "Điện thoại",
  "district": "Quận 9",
  "status": "Active",
  "condition": "Đồ cũ",
  "title": "Bán Iphone 13 Pro Max xài lướt",
  "price": 10000000,
  "description": "Bán gấp Iphone 13 Pro Max, chỉ 20 triệu liên hệ ngay để ép giá!",
  "productDetails": {
    "color": "xanh"
  }
}

###
PUT http://localhost:5000/api/posts/viewCount/624ea0f71e88fd8a60835eff
Content-Type: application/json

###


PUT http://localhost:5000/api/posts/repost/624ea0f71e88fd8a60835eff
Content-Type: application/json
###

PUT http://localhost:5000/api/posts/close-post/624ea0f71e88fd8a60835eff
Content-Type: application/json
###

PUT http://localhost:5000/api/posts/624ea0f71e88fd8a60835eff
Content-Type: application/json

{
  "category": "Đồ điện tử",
  "subCategory": "Điện thoại",
  "zaloId": "3024770787876860996",
  "city": "Thủ Đức",
  "district": "Quận 9",
  "status": "Active",
  "images": ["https://i.imgur.com/TyPdN9n.jpeg"],
  "condition": "Đồ cũ",
  "title": "Bán Iphone 13 Pro Max xài lướt",
  "price": 30000000,
  "description": "Bán gấp Iphone 13 Pro Max, chỉ 20 triệu liên hệ ngay để ép giá!",
  "productDetails": {
    "color": "đen"
  }
}

###
// lấy danh sách post của 1 user
GET http://localhost:5000/api/posts/by-user/3024770787876860996
Content-Type: application/json
